<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Dudi;
use App\Models\Booking;
use Illuminate\Support\Facades\DB;

class DudiSeeder extends Seeder
{
    public function run()
    {
        // Clear existing data
        Booking::truncate();
        Dudi::truncate();
        
        // Sample DUDI data
        $dudis = [
            ['nama_dudi' => 'PT. Telkom Indonesia Malang', 'bidang_usaha' => 'Telekomunikasi', 'alamat' => 'Jl. Sudanco Supriyadi No. 1, Malang', 'telepon' => '(0341) 300123', 'email' => 'hrd@telkom-malang.co.id', 'deskripsi' => 'Perusahaan telekomunikasi terkemuka yang menyediakan layanan internet, telepon, dan TV kabel.', 'kota' => 'Kota Malang', 'kuota' => 12, 'jam_masuk' => '07.00', 'jam_pulang' => '16.00', 'pembimbing_dudi' => 'Ir. Suryanto Wijaya'],
            ['nama_dudi' => 'CV. Maju Digital Indonesia', 'bidang_usaha' => 'Teknologi Informasi', 'alamat' => 'Jl. Sutoyo No. 45, Malang', 'telepon' => '(0341) 555001', 'email' => 'karir@majudigital.com', 'deskripsi' => 'Perusahaan IT yang spesialis dalam pengembangan software web dan mobile applications.', 'kota' => 'Kota Malang', 'kuota' => 8, 'jam_masuk' => '08.00', 'jam_pulang' => '17.00', 'pembimbing_dudi' => 'Budi Santoso S.Kom'],
            ['nama_dudi' => 'PT. Cipta Electrical', 'bidang_usaha' => 'Manufaktur Elektronik', 'alamat' => 'Jl. Raya Tlogomas No. 123, Malang', 'telepon' => '(0341) 777234', 'email' => 'hr@ciptaelectrical.com', 'deskripsi' => 'Produsen komponen elektronik dengan standar internasional untuk industri otomotif dan telekomunikasi.', 'kota' => 'Kota Malang', 'kuota' => 10, 'jam_masuk' => '06.30', 'jam_pulang' => '15.30', 'pembimbing_dudi' => 'Eng. Priyanto Handoko'],
            ['nama_dudi' => 'Koperasi Tani Sejahtera', 'bidang_usaha' => 'Pertanian & Perkebunan', 'alamat' => 'Jl. Gajayana No. 567, Malang', 'telepon' => '(0341) 444876', 'email' => 'info@kopersani.org', 'deskripsi' => 'Koperasi yang menangani agrobisnis, pengolahan hasil pertanian dan pemasaran produk organik.', 'kota' => 'Kota Malang', 'kuota' => 6, 'jam_masuk' => '07.00', 'jam_pulang' => '15.00', 'pembimbing_dudi' => 'Drs. Haryanto Wijaya'],
            ['nama_dudi' => 'Hotel Bintang Lima Malang', 'bidang_usaha' => 'Perhotelan & Pariwisata', 'alamat' => 'Jl. Ijen No. 1, Malang', 'telepon' => '(0341) 360000', 'email' => 'hr@hotelmalang.com', 'deskripsi' => 'Hotel bintang lima yang menyediakan layanan akomodasi premium dengan standar internasional.', 'kota' => 'Kota Malang', 'kuota' => 5, 'jam_masuk' => '07.00', 'jam_pulang' => '15.00', 'pembimbing_dudi' => 'Ibu Siti Nurhaliza'],
            ['nama_dudi' => 'PT. Garuda Jaya Transportasi', 'bidang_usaha' => 'Transportasi & Logistik', 'alamat' => 'Jl. Raya Sukun No. 234, Malang', 'telepon' => '(0341) 660789', 'email' => 'operator@garudajaya.com', 'deskripsi' => 'Perusahaan transportasi dan logistik yang melayani pengiriman barang regional dan nasional.', 'kota' => 'Kota Malang', 'kuota' => 7, 'jam_masuk' => '06.00', 'jam_pulang' => '15.00', 'pembimbing_dudi' => 'Pak Bambang Irawan'],
            ['nama_dudi' => 'PT. Citra Jaya Kontruksi', 'bidang_usaha' => 'Konstruksi & Bangunan', 'alamat' => 'Jl. Martadinata No. 890, Malang', 'telepon' => '(0341) 771122', 'email' => 'proyek@citrajaya.co.id', 'deskripsi' => 'Perusahaan konstruksi yang mengerjakan proyek infrastruktur, gedung, dan real estate komersial.', 'kota' => 'Kota Malang', 'kuota' => 9, 'jam_masuk' => '07.00', 'jam_pulang' => '16.00', 'pembimbing_dudi' => 'Ir. Widodo Santoso'],
            ['nama_dudi' => 'Rumah Sakit Permata Medika', 'bidang_usaha' => 'Kesehatan & Medis', 'alamat' => 'Jl. Ahmad Yani No. 456, Malang', 'telepon' => '(0341) 333456', 'email' => 'hr@permatamemedika.com', 'deskripsi' => 'Rumah sakit modern dengan fasilitas kesehatan lengkap dan tenaga medis profesional.', 'kota' => 'Kota Malang', 'kuota' => 4, 'jam_masuk' => '07.00', 'jam_pulang' => '15.00', 'pembimbing_dudi' => 'Dr. Hendra Susanto'],
            ['nama_dudi' => 'PT. Jaya Abadi Retail', 'bidang_usaha' => 'Ritel & Penjualan', 'alamat' => 'Jl. Besar No. 100, Malang', 'telepon' => '(0341) 222333', 'email' => 'store@jayaabadi.com', 'deskripsi' => 'Perusahaan retail dengan jaringan toko yang luas menjual berbagai kebutuhan sehari-hari.', 'kota' => 'Kota Malang', 'kuota' => 11, 'jam_masuk' => '09.00', 'jam_pulang' => '18.00', 'pembimbing_dudi' => 'Ibu Yeni Hartono'],
            ['nama_dudi' => 'Kantor Akuntan Publik Mitra', 'bidang_usaha' => 'Jasa Keuangan & Akuntansi', 'alamat' => 'Jl. Basuki Rahmat No. 789, Malang', 'telepon' => '(0341) 888999', 'email' => 'info@kap-mitra.com', 'deskripsi' => 'Kantor akuntan publik yang memberikan layanan audit, konsultasi, dan perpajakan bisnis.', 'kota' => 'Kota Malang', 'kuota' => 3, 'jam_masuk' => '08.00', 'jam_pulang' => '17.00', 'pembimbing_dudi' => 'Pak Hendra Wijaya CPA'],
            ['nama_dudi' => 'PT. Mitra Media Kreatif', 'bidang_usaha' => 'Media & Periklanan', 'alamat' => 'Jl. Diponegoro No. 321, Malang', 'telepon' => '(0341) 666777', 'email' => 'studio@mitra-media.co.id', 'deskripsi' => 'Agensi kreatif yang menghasilkan konten media, iklan digital, dan branding untuk berbagai klien.', 'kota' => 'Kota Malang', 'kuota' => 6, 'jam_masuk' => '09.00', 'jam_pulang' => '18.00', 'pembimbing_dudi' => 'Mas Ade Sugito'],
            ['nama_dudi' => 'Sekolah Internasional Malang', 'bidang_usaha' => 'Pendidikan', 'alamat' => 'Jl. Raya Buring No. 567, Malang', 'telepon' => '(0341) 444333', 'email' => 'admin@sim-malang.sch.id', 'deskripsi' => 'Sekolah internasional yang menyediakan pendidikan berkualitas dengan kurikulum internasional.', 'kota' => 'Kota Malang', 'kuota' => 5, 'jam_masuk' => '07.00', 'jam_pulang' => '14.30', 'pembimbing_dudi' => 'Mrs. Rianti Sukoco M.Ed'],
            ['nama_dudi' => 'PT. Pupuk Sriwijaya Surabaya', 'bidang_usaha' => 'Industri Kimia', 'alamat' => 'Jl. Raya Tandes, Surabaya', 'telepon' => '(031) 7411234', 'email' => 'hr@pupuk-sriwijaya.com', 'deskripsi' => 'Produsen pupuk dan bahan kimia untuk pertanian dengan teknologi modern.', 'kota' => 'Kota Surabaya', 'kuota' => 15, 'jam_masuk' => '07.00', 'jam_pulang' => '15.00', 'pembimbing_dudi' => 'Ing. Bambang Suryanto'],
            ['nama_dudi' => 'Bank Jaya Raya Surabaya', 'bidang_usaha' => 'Perbankan', 'alamat' => 'Jl. Pemuda No. 1, Surabaya', 'telepon' => '(031) 5464444', 'email' => 'career@bankjaya.co.id', 'deskripsi' => 'Bank komersial yang menyediakan layanan perbankan untuk individu dan korporat.', 'kota' => 'Kota Surabaya', 'kuota' => 8, 'jam_masuk' => '08.00', 'jam_pulang' => '16.00', 'pembimbing_dudi' => 'Ibu Suhartini'],
            ['nama_dudi' => 'PT. Semen Gresik Surabaya', 'bidang_usaha' => 'Industri Semen', 'alamat' => 'Jl. Raya Gresik, Surabaya', 'telepon' => '(031) 3999999', 'email' => 'karir@semengresik.co.id', 'deskripsi' => 'Produsen semen berkualitas untuk industri konstruksi nasional dan regional.', 'kota' => 'Kota Surabaya', 'kuota' => 20, 'jam_masuk' => '06.00', 'jam_pulang' => '15.00', 'pembimbing_dudi' => 'Pak Sudarno Wibowo'],
            ['nama_dudi' => 'PT. Garuda Indonesia Maintenance', 'bidang_usaha' => 'Penerbangan', 'alamat' => 'Bandara Internasional Juanda, Surabaya', 'telepon' => '(031) 8664600', 'email' => 'hr@garudamaint.com', 'deskripsi' => 'Layanan maintenance dan perbaikan pesawat untuk maskapai penerbangan nasional.', 'kota' => 'Kota Surabaya', 'kuota' => 16, 'jam_masuk' => '07.00', 'jam_pulang' => '16.00', 'pembimbing_dudi' => 'Eng. Joni Pratama'],
            ['nama_dudi' => 'PT. Pelabuhan Tanjung Perak', 'bidang_usaha' => 'Pelabuhan & Logistik', 'alamat' => 'Jl. Tanjung Perak, Surabaya', 'telepon' => '(031) 3281108', 'email' => 'recruitment@pelabuhansby.co.id', 'deskripsi' => 'Operator pelabuhan utama yang menangani bongkar muat container dan cargo.', 'kota' => 'Kota Surabaya', 'kuota' => 12, 'jam_masuk' => '06.00', 'jam_pulang' => '14.00', 'pembimbing_dudi' => 'Kapt. Wahyu Hermawan'],
            ['nama_dudi' => 'PT. Petrokimia Gresik', 'bidang_usaha' => 'Industri Petrokimia', 'alamat' => 'Gresik, Jawa Timur', 'telepon' => '(031) 3981000', 'email' => 'hr@petrokimia-gresik.com', 'deskripsi' => 'Produsen bahan petrokimia dan produk turunan untuk berbagai industri.', 'kota' => 'Kota Surabaya', 'kuota' => 18, 'jam_masuk' => '06.30', 'jam_pulang' => '15.30', 'pembimbing_dudi' => 'Ir. Slamet Budiono'],
            ['nama_dudi' => 'RS. Universitas Airlangga', 'bidang_usaha' => 'Kesehatan', 'alamat' => 'Jl. Mayjend Prof. Dr. Moestopo, Surabaya', 'telepon' => '(031) 5016800', 'email' => 'hr@rsuia.net', 'deskripsi' => 'Rumah sakit akademik yang menggabungkan pelayanan kesehatan dengan pendidikan medis.', 'kota' => 'Kota Surabaya', 'kuota' => 7, 'jam_masuk' => '07.00', 'jam_pulang' => '15.00', 'pembimbing_dudi' => 'Dr. Mohamad Syaiful'],
            ['nama_dudi' => 'PT. Industri Tekstil Mitra Nusa', 'bidang_usaha' => 'Tekstil & Garmen', 'alamat' => 'Jl. Veteran No. 456, Surabaya', 'telepon' => '(031) 7891234', 'email' => 'karir@itmn.co.id', 'deskripsi' => 'Pabrik tekstil dan garmen yang memproduksi kain dan pakaian untuk pasar lokal dan ekspor.', 'kota' => 'Kota Surabaya', 'kuota' => 10, 'jam_masuk' => '07.00', 'jam_pulang' => '16.00', 'pembimbing_dudi' => 'Bu Etika Maharani'],
            ['nama_dudi' => 'PT. Buah Nusantara Batu', 'bidang_usaha' => 'Agribisnis Buah', 'alamat' => 'Jl. Raya Batu Kota Batu', 'telepon' => '(0341) 595000', 'email' => 'info@buahnusantara.com', 'deskripsi' => 'Perkebunan apel dan buah-buahan lain yang memproduksi dan memasarkan buah berkualitas tinggi.', 'kota' => 'Kota Batu', 'kuota' => 4, 'jam_masuk' => '06.00', 'jam_pulang' => '14.00', 'pembimbing_dudi' => 'Bapak Suwandi'],
            ['nama_dudi' => 'Wisata Taman Bunga Batu', 'bidang_usaha' => 'Pariwisata', 'alamat' => 'Jl. Pendem, Kota Batu', 'telepon' => '(0341) 322788', 'email' => 'admin@tamanbunga.org', 'deskripsi' => 'Objek wisata taman bunga yang menyediakan fasilitas rekreasi dan hotel untuk pengunjung.', 'kota' => 'Kota Batu', 'kuota' => 6, 'jam_masuk' => '08.00', 'jam_pulang' => '17.00', 'pembimbing_dudi' => 'Ibu Herawati Suwisno'],
            ['nama_dudi' => 'Pabrik Keramik Indah Batu', 'bidang_usaha' => 'Industri Keramik', 'alamat' => 'Jl. Bedali, Kota Batu', 'telepon' => '(0341) 566333', 'email' => 'produksi@keramilndah.com', 'deskripsi' => 'Pabrik keramik yang menghasilkan produk keramik dekoratif dan fungsional.', 'kota' => 'Kota Batu', 'kuota' => 5, 'jam_masuk' => '07.00', 'jam_pulang' => '15.00', 'pembimbing_dudi' => 'Pak Noto Winarno'],
        ];
        
        foreach ($dudis as $dudi) {
            Dudi::create($dudi);
        }
    }
}
